package com.yh.web.mapper;

import com.yh.web.pojo.BookBorrow;
import com.yh.web.pojo.BookBorrowExample;
import com.yh.web.pojo.BookBorrowKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookBorrowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_borrow
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    long countByExample(BookBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_borrow
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int deleteByExample(BookBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_borrow
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int deleteByPrimaryKey(BookBorrowKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_borrow
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int insert(BookBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_borrow
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int insertSelective(BookBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_borrow
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    List<BookBorrow> selectByExample(BookBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_borrow
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    BookBorrow selectByPrimaryKey(BookBorrowKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_borrow
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByExampleSelective(@Param("record") BookBorrow record, @Param("example") BookBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_borrow
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByExample(@Param("record") BookBorrow record, @Param("example") BookBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_borrow
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByPrimaryKeySelective(BookBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_borrow
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByPrimaryKey(BookBorrow record);
}