package com.yh.web.mapper;

import com.yh.web.pojo.BookStatus;
import com.yh.web.pojo.BookStatusExample;
import com.yh.web.pojo.BookStatusKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    long countByExample(BookStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int deleteByExample(BookStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int deleteByPrimaryKey(BookStatusKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int insert(BookStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int insertSelective(BookStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    List<BookStatus> selectByExample(BookStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    BookStatus selectByPrimaryKey(BookStatusKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByExampleSelective(@Param("record") BookStatus record, @Param("example") BookStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByExample(@Param("record") BookStatus record, @Param("example") BookStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByPrimaryKeySelective(BookStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByPrimaryKey(BookStatus record);
}