package com.yh.web.mapper;

import com.yh.web.pojo.BookAll;
import com.yh.web.pojo.BookAllExample;
import com.yh.web.pojo.BookAllKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookAllMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    long countByExample(BookAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int deleteByExample(BookAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int deleteByPrimaryKey(BookAllKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int insert(BookAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int insertSelective(BookAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    List<BookAll> selectByExample(BookAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    BookAll selectByPrimaryKey(BookAllKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByExampleSelective(@Param("record") BookAll record, @Param("example") BookAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByExample(@Param("record") BookAll record, @Param("example") BookAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByPrimaryKeySelective(BookAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByPrimaryKey(BookAll record);
}