package com.yh.web.mapper;

import com.yh.web.pojo.BookType;
import com.yh.web.pojo.BookTypeExample;
import com.yh.web.pojo.BookTypeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    long countByExample(BookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int deleteByExample(BookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int deleteByPrimaryKey(BookTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int insert(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int insertSelective(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    List<BookType> selectByExample(BookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    BookType selectByPrimaryKey(BookTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByExampleSelective(@Param("record") BookType record, @Param("example") BookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByExample(@Param("record") BookType record, @Param("example") BookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByPrimaryKeySelective(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    int updateByPrimaryKey(BookType record);
}