package com.yh.web.pojo;

public class BookBorrowKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_borrow.borrow_id
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private Integer borrowId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_borrow.borrow_id
     *
     * @return the value of t_book_borrow.borrow_id
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public Integer getBorrowId() {
        return borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_borrow.borrow_id
     *
     * @param borrowId the value for t_book_borrow.borrow_id
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setBorrowId(Integer borrowId) {
        this.borrowId = borrowId;
    }
}