package com.yh.web.pojo;

public class BookTypeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_type.book_type_id
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private Integer bookTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_type.book_type_id
     *
     * @return the value of t_book_type.book_type_id
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public Integer getBookTypeId() {
        return bookTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_type.book_type_id
     *
     * @param bookTypeId the value for t_book_type.book_type_id
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setBookTypeId(Integer bookTypeId) {
        this.bookTypeId = bookTypeId;
    }
}