package com.yh.web.pojo;

public class BookStatus extends BookStatusKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_status.status_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private String statusType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_status.status_demo
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private String statusDemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_status.status_type
     *
     * @return the value of t_book_status.status_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getStatusType() {
        return statusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_status.status_type
     *
     * @param statusType the value for t_book_status.status_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setStatusType(String statusType) {
        this.statusType = statusType == null ? null : statusType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_status.status_demo
     *
     * @return the value of t_book_status.status_demo
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getStatusDemo() {
        return statusDemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_status.status_demo
     *
     * @param statusDemo the value for t_book_status.status_demo
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setStatusDemo(String statusDemo) {
        this.statusDemo = statusDemo == null ? null : statusDemo.trim();
    }
}