package com.yh.web.pojo;

public class BookAllKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_all.book_id
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private Integer bookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_all.book_id
     *
     * @return the value of t_book_all.book_id
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_all.book_id
     *
     * @param bookId the value for t_book_all.book_id
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
}