package com.yh.web.pojo;

import java.util.Date;

public class BookBorrow extends BookBorrowKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_borrow.book_ISBN
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private String bookIsbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_borrow.ordinary_number
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private String ordinaryNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_borrow.borrow_loan_date
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private Date borrowLoanDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_borrow.borrow_return_date
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private Date borrowReturnDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_borrow.book_ISBN
     *
     * @return the value of t_book_borrow.book_ISBN
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getBookIsbn() {
        return bookIsbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_borrow.book_ISBN
     *
     * @param bookIsbn the value for t_book_borrow.book_ISBN
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setBookIsbn(String bookIsbn) {
        this.bookIsbn = bookIsbn == null ? null : bookIsbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_borrow.ordinary_number
     *
     * @return the value of t_book_borrow.ordinary_number
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getOrdinaryNumber() {
        return ordinaryNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_borrow.ordinary_number
     *
     * @param ordinaryNumber the value for t_book_borrow.ordinary_number
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrdinaryNumber(String ordinaryNumber) {
        this.ordinaryNumber = ordinaryNumber == null ? null : ordinaryNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_borrow.borrow_loan_date
     *
     * @return the value of t_book_borrow.borrow_loan_date
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public Date getBorrowLoanDate() {
        return borrowLoanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_borrow.borrow_loan_date
     *
     * @param borrowLoanDate the value for t_book_borrow.borrow_loan_date
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setBorrowLoanDate(Date borrowLoanDate) {
        this.borrowLoanDate = borrowLoanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_borrow.borrow_return_date
     *
     * @return the value of t_book_borrow.borrow_return_date
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public Date getBorrowReturnDate() {
        return borrowReturnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_borrow.borrow_return_date
     *
     * @param borrowReturnDate the value for t_book_borrow.borrow_return_date
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setBorrowReturnDate(Date borrowReturnDate) {
        this.borrowReturnDate = borrowReturnDate;
    }
}