package com.yh.web.pojo;

import java.util.ArrayList;
import java.util.List;

public class BookStatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public BookStatusExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStatusIdIsNull() {
            addCriterion("status_id is null");
            return (Criteria) this;
        }

        public Criteria andStatusIdIsNotNull() {
            addCriterion("status_id is not null");
            return (Criteria) this;
        }

        public Criteria andStatusIdEqualTo(Integer value) {
            addCriterion("status_id =", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotEqualTo(Integer value) {
            addCriterion("status_id <>", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdGreaterThan(Integer value) {
            addCriterion("status_id >", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("status_id >=", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdLessThan(Integer value) {
            addCriterion("status_id <", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdLessThanOrEqualTo(Integer value) {
            addCriterion("status_id <=", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdIn(List<Integer> values) {
            addCriterion("status_id in", values, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotIn(List<Integer> values) {
            addCriterion("status_id not in", values, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdBetween(Integer value1, Integer value2) {
            addCriterion("status_id between", value1, value2, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotBetween(Integer value1, Integer value2) {
            addCriterion("status_id not between", value1, value2, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusTypeIsNull() {
            addCriterion("status_type is null");
            return (Criteria) this;
        }

        public Criteria andStatusTypeIsNotNull() {
            addCriterion("status_type is not null");
            return (Criteria) this;
        }

        public Criteria andStatusTypeEqualTo(String value) {
            addCriterion("status_type =", value, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeNotEqualTo(String value) {
            addCriterion("status_type <>", value, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeGreaterThan(String value) {
            addCriterion("status_type >", value, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeGreaterThanOrEqualTo(String value) {
            addCriterion("status_type >=", value, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeLessThan(String value) {
            addCriterion("status_type <", value, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeLessThanOrEqualTo(String value) {
            addCriterion("status_type <=", value, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeLike(String value) {
            addCriterion("status_type like", value, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeNotLike(String value) {
            addCriterion("status_type not like", value, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeIn(List<String> values) {
            addCriterion("status_type in", values, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeNotIn(List<String> values) {
            addCriterion("status_type not in", values, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeBetween(String value1, String value2) {
            addCriterion("status_type between", value1, value2, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeNotBetween(String value1, String value2) {
            addCriterion("status_type not between", value1, value2, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusDemoIsNull() {
            addCriterion("status_demo is null");
            return (Criteria) this;
        }

        public Criteria andStatusDemoIsNotNull() {
            addCriterion("status_demo is not null");
            return (Criteria) this;
        }

        public Criteria andStatusDemoEqualTo(String value) {
            addCriterion("status_demo =", value, "statusDemo");
            return (Criteria) this;
        }

        public Criteria andStatusDemoNotEqualTo(String value) {
            addCriterion("status_demo <>", value, "statusDemo");
            return (Criteria) this;
        }

        public Criteria andStatusDemoGreaterThan(String value) {
            addCriterion("status_demo >", value, "statusDemo");
            return (Criteria) this;
        }

        public Criteria andStatusDemoGreaterThanOrEqualTo(String value) {
            addCriterion("status_demo >=", value, "statusDemo");
            return (Criteria) this;
        }

        public Criteria andStatusDemoLessThan(String value) {
            addCriterion("status_demo <", value, "statusDemo");
            return (Criteria) this;
        }

        public Criteria andStatusDemoLessThanOrEqualTo(String value) {
            addCriterion("status_demo <=", value, "statusDemo");
            return (Criteria) this;
        }

        public Criteria andStatusDemoLike(String value) {
            addCriterion("status_demo like", value, "statusDemo");
            return (Criteria) this;
        }

        public Criteria andStatusDemoNotLike(String value) {
            addCriterion("status_demo not like", value, "statusDemo");
            return (Criteria) this;
        }

        public Criteria andStatusDemoIn(List<String> values) {
            addCriterion("status_demo in", values, "statusDemo");
            return (Criteria) this;
        }

        public Criteria andStatusDemoNotIn(List<String> values) {
            addCriterion("status_demo not in", values, "statusDemo");
            return (Criteria) this;
        }

        public Criteria andStatusDemoBetween(String value1, String value2) {
            addCriterion("status_demo between", value1, value2, "statusDemo");
            return (Criteria) this;
        }

        public Criteria andStatusDemoNotBetween(String value1, String value2) {
            addCriterion("status_demo not between", value1, value2, "statusDemo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_book_status
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 14 13:07:44 AWST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_book_status
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}