package com.yh.web.pojo;

import java.util.ArrayList;
import java.util.List;

public class BookTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public BookTypeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBookTypeIdIsNull() {
            addCriterion("book_type_id is null");
            return (Criteria) this;
        }

        public Criteria andBookTypeIdIsNotNull() {
            addCriterion("book_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andBookTypeIdEqualTo(Integer value) {
            addCriterion("book_type_id =", value, "bookTypeId");
            return (Criteria) this;
        }

        public Criteria andBookTypeIdNotEqualTo(Integer value) {
            addCriterion("book_type_id <>", value, "bookTypeId");
            return (Criteria) this;
        }

        public Criteria andBookTypeIdGreaterThan(Integer value) {
            addCriterion("book_type_id >", value, "bookTypeId");
            return (Criteria) this;
        }

        public Criteria andBookTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("book_type_id >=", value, "bookTypeId");
            return (Criteria) this;
        }

        public Criteria andBookTypeIdLessThan(Integer value) {
            addCriterion("book_type_id <", value, "bookTypeId");
            return (Criteria) this;
        }

        public Criteria andBookTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("book_type_id <=", value, "bookTypeId");
            return (Criteria) this;
        }

        public Criteria andBookTypeIdIn(List<Integer> values) {
            addCriterion("book_type_id in", values, "bookTypeId");
            return (Criteria) this;
        }

        public Criteria andBookTypeIdNotIn(List<Integer> values) {
            addCriterion("book_type_id not in", values, "bookTypeId");
            return (Criteria) this;
        }

        public Criteria andBookTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("book_type_id between", value1, value2, "bookTypeId");
            return (Criteria) this;
        }

        public Criteria andBookTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("book_type_id not between", value1, value2, "bookTypeId");
            return (Criteria) this;
        }

        public Criteria andBookTypeNameIsNull() {
            addCriterion("book_type_name is null");
            return (Criteria) this;
        }

        public Criteria andBookTypeNameIsNotNull() {
            addCriterion("book_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andBookTypeNameEqualTo(String value) {
            addCriterion("book_type_name =", value, "bookTypeName");
            return (Criteria) this;
        }

        public Criteria andBookTypeNameNotEqualTo(String value) {
            addCriterion("book_type_name <>", value, "bookTypeName");
            return (Criteria) this;
        }

        public Criteria andBookTypeNameGreaterThan(String value) {
            addCriterion("book_type_name >", value, "bookTypeName");
            return (Criteria) this;
        }

        public Criteria andBookTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("book_type_name >=", value, "bookTypeName");
            return (Criteria) this;
        }

        public Criteria andBookTypeNameLessThan(String value) {
            addCriterion("book_type_name <", value, "bookTypeName");
            return (Criteria) this;
        }

        public Criteria andBookTypeNameLessThanOrEqualTo(String value) {
            addCriterion("book_type_name <=", value, "bookTypeName");
            return (Criteria) this;
        }

        public Criteria andBookTypeNameLike(String value) {
            addCriterion("book_type_name like", value, "bookTypeName");
            return (Criteria) this;
        }

        public Criteria andBookTypeNameNotLike(String value) {
            addCriterion("book_type_name not like", value, "bookTypeName");
            return (Criteria) this;
        }

        public Criteria andBookTypeNameIn(List<String> values) {
            addCriterion("book_type_name in", values, "bookTypeName");
            return (Criteria) this;
        }

        public Criteria andBookTypeNameNotIn(List<String> values) {
            addCriterion("book_type_name not in", values, "bookTypeName");
            return (Criteria) this;
        }

        public Criteria andBookTypeNameBetween(String value1, String value2) {
            addCriterion("book_type_name between", value1, value2, "bookTypeName");
            return (Criteria) this;
        }

        public Criteria andBookTypeNameNotBetween(String value1, String value2) {
            addCriterion("book_type_name not between", value1, value2, "bookTypeName");
            return (Criteria) this;
        }

        public Criteria andBookTypeDemoIsNull() {
            addCriterion("book_type_demo is null");
            return (Criteria) this;
        }

        public Criteria andBookTypeDemoIsNotNull() {
            addCriterion("book_type_demo is not null");
            return (Criteria) this;
        }

        public Criteria andBookTypeDemoEqualTo(String value) {
            addCriterion("book_type_demo =", value, "bookTypeDemo");
            return (Criteria) this;
        }

        public Criteria andBookTypeDemoNotEqualTo(String value) {
            addCriterion("book_type_demo <>", value, "bookTypeDemo");
            return (Criteria) this;
        }

        public Criteria andBookTypeDemoGreaterThan(String value) {
            addCriterion("book_type_demo >", value, "bookTypeDemo");
            return (Criteria) this;
        }

        public Criteria andBookTypeDemoGreaterThanOrEqualTo(String value) {
            addCriterion("book_type_demo >=", value, "bookTypeDemo");
            return (Criteria) this;
        }

        public Criteria andBookTypeDemoLessThan(String value) {
            addCriterion("book_type_demo <", value, "bookTypeDemo");
            return (Criteria) this;
        }

        public Criteria andBookTypeDemoLessThanOrEqualTo(String value) {
            addCriterion("book_type_demo <=", value, "bookTypeDemo");
            return (Criteria) this;
        }

        public Criteria andBookTypeDemoLike(String value) {
            addCriterion("book_type_demo like", value, "bookTypeDemo");
            return (Criteria) this;
        }

        public Criteria andBookTypeDemoNotLike(String value) {
            addCriterion("book_type_demo not like", value, "bookTypeDemo");
            return (Criteria) this;
        }

        public Criteria andBookTypeDemoIn(List<String> values) {
            addCriterion("book_type_demo in", values, "bookTypeDemo");
            return (Criteria) this;
        }

        public Criteria andBookTypeDemoNotIn(List<String> values) {
            addCriterion("book_type_demo not in", values, "bookTypeDemo");
            return (Criteria) this;
        }

        public Criteria andBookTypeDemoBetween(String value1, String value2) {
            addCriterion("book_type_demo between", value1, value2, "bookTypeDemo");
            return (Criteria) this;
        }

        public Criteria andBookTypeDemoNotBetween(String value1, String value2) {
            addCriterion("book_type_demo not between", value1, value2, "bookTypeDemo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_book_type
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 14 13:07:44 AWST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_book_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}