package com.yh.web.pojo;

public class UserOrdinaryKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ordinary.ordinary_id
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private Integer ordinaryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ordinary.ordinary_id
     *
     * @return the value of t_user_ordinary.ordinary_id
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public Integer getOrdinaryId() {
        return ordinaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ordinary.ordinary_id
     *
     * @param ordinaryId the value for t_user_ordinary.ordinary_id
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrdinaryId(Integer ordinaryId) {
        this.ordinaryId = ordinaryId;
    }
}