package com.yh.web.pojo;

import java.util.ArrayList;
import java.util.List;

public class UserOrdinaryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public UserOrdinaryExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrdinaryIdIsNull() {
            addCriterion("ordinary_id is null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryIdIsNotNull() {
            addCriterion("ordinary_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryIdEqualTo(Integer value) {
            addCriterion("ordinary_id =", value, "ordinaryId");
            return (Criteria) this;
        }

        public Criteria andOrdinaryIdNotEqualTo(Integer value) {
            addCriterion("ordinary_id <>", value, "ordinaryId");
            return (Criteria) this;
        }

        public Criteria andOrdinaryIdGreaterThan(Integer value) {
            addCriterion("ordinary_id >", value, "ordinaryId");
            return (Criteria) this;
        }

        public Criteria andOrdinaryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ordinary_id >=", value, "ordinaryId");
            return (Criteria) this;
        }

        public Criteria andOrdinaryIdLessThan(Integer value) {
            addCriterion("ordinary_id <", value, "ordinaryId");
            return (Criteria) this;
        }

        public Criteria andOrdinaryIdLessThanOrEqualTo(Integer value) {
            addCriterion("ordinary_id <=", value, "ordinaryId");
            return (Criteria) this;
        }

        public Criteria andOrdinaryIdIn(List<Integer> values) {
            addCriterion("ordinary_id in", values, "ordinaryId");
            return (Criteria) this;
        }

        public Criteria andOrdinaryIdNotIn(List<Integer> values) {
            addCriterion("ordinary_id not in", values, "ordinaryId");
            return (Criteria) this;
        }

        public Criteria andOrdinaryIdBetween(Integer value1, Integer value2) {
            addCriterion("ordinary_id between", value1, value2, "ordinaryId");
            return (Criteria) this;
        }

        public Criteria andOrdinaryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ordinary_id not between", value1, value2, "ordinaryId");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNumberIsNull() {
            addCriterion("ordinary_number is null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNumberIsNotNull() {
            addCriterion("ordinary_number is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNumberEqualTo(String value) {
            addCriterion("ordinary_number =", value, "ordinaryNumber");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNumberNotEqualTo(String value) {
            addCriterion("ordinary_number <>", value, "ordinaryNumber");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNumberGreaterThan(String value) {
            addCriterion("ordinary_number >", value, "ordinaryNumber");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNumberGreaterThanOrEqualTo(String value) {
            addCriterion("ordinary_number >=", value, "ordinaryNumber");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNumberLessThan(String value) {
            addCriterion("ordinary_number <", value, "ordinaryNumber");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNumberLessThanOrEqualTo(String value) {
            addCriterion("ordinary_number <=", value, "ordinaryNumber");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNumberLike(String value) {
            addCriterion("ordinary_number like", value, "ordinaryNumber");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNumberNotLike(String value) {
            addCriterion("ordinary_number not like", value, "ordinaryNumber");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNumberIn(List<String> values) {
            addCriterion("ordinary_number in", values, "ordinaryNumber");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNumberNotIn(List<String> values) {
            addCriterion("ordinary_number not in", values, "ordinaryNumber");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNumberBetween(String value1, String value2) {
            addCriterion("ordinary_number between", value1, value2, "ordinaryNumber");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNumberNotBetween(String value1, String value2) {
            addCriterion("ordinary_number not between", value1, value2, "ordinaryNumber");
            return (Criteria) this;
        }

        public Criteria andOrdinaryUsernameIsNull() {
            addCriterion("ordinary_username is null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryUsernameIsNotNull() {
            addCriterion("ordinary_username is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryUsernameEqualTo(String value) {
            addCriterion("ordinary_username =", value, "ordinaryUsername");
            return (Criteria) this;
        }

        public Criteria andOrdinaryUsernameNotEqualTo(String value) {
            addCriterion("ordinary_username <>", value, "ordinaryUsername");
            return (Criteria) this;
        }

        public Criteria andOrdinaryUsernameGreaterThan(String value) {
            addCriterion("ordinary_username >", value, "ordinaryUsername");
            return (Criteria) this;
        }

        public Criteria andOrdinaryUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("ordinary_username >=", value, "ordinaryUsername");
            return (Criteria) this;
        }

        public Criteria andOrdinaryUsernameLessThan(String value) {
            addCriterion("ordinary_username <", value, "ordinaryUsername");
            return (Criteria) this;
        }

        public Criteria andOrdinaryUsernameLessThanOrEqualTo(String value) {
            addCriterion("ordinary_username <=", value, "ordinaryUsername");
            return (Criteria) this;
        }

        public Criteria andOrdinaryUsernameLike(String value) {
            addCriterion("ordinary_username like", value, "ordinaryUsername");
            return (Criteria) this;
        }

        public Criteria andOrdinaryUsernameNotLike(String value) {
            addCriterion("ordinary_username not like", value, "ordinaryUsername");
            return (Criteria) this;
        }

        public Criteria andOrdinaryUsernameIn(List<String> values) {
            addCriterion("ordinary_username in", values, "ordinaryUsername");
            return (Criteria) this;
        }

        public Criteria andOrdinaryUsernameNotIn(List<String> values) {
            addCriterion("ordinary_username not in", values, "ordinaryUsername");
            return (Criteria) this;
        }

        public Criteria andOrdinaryUsernameBetween(String value1, String value2) {
            addCriterion("ordinary_username between", value1, value2, "ordinaryUsername");
            return (Criteria) this;
        }

        public Criteria andOrdinaryUsernameNotBetween(String value1, String value2) {
            addCriterion("ordinary_username not between", value1, value2, "ordinaryUsername");
            return (Criteria) this;
        }

        public Criteria andOrdinaryPasswordIsNull() {
            addCriterion("ordinary_password is null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryPasswordIsNotNull() {
            addCriterion("ordinary_password is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryPasswordEqualTo(String value) {
            addCriterion("ordinary_password =", value, "ordinaryPassword");
            return (Criteria) this;
        }

        public Criteria andOrdinaryPasswordNotEqualTo(String value) {
            addCriterion("ordinary_password <>", value, "ordinaryPassword");
            return (Criteria) this;
        }

        public Criteria andOrdinaryPasswordGreaterThan(String value) {
            addCriterion("ordinary_password >", value, "ordinaryPassword");
            return (Criteria) this;
        }

        public Criteria andOrdinaryPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("ordinary_password >=", value, "ordinaryPassword");
            return (Criteria) this;
        }

        public Criteria andOrdinaryPasswordLessThan(String value) {
            addCriterion("ordinary_password <", value, "ordinaryPassword");
            return (Criteria) this;
        }

        public Criteria andOrdinaryPasswordLessThanOrEqualTo(String value) {
            addCriterion("ordinary_password <=", value, "ordinaryPassword");
            return (Criteria) this;
        }

        public Criteria andOrdinaryPasswordLike(String value) {
            addCriterion("ordinary_password like", value, "ordinaryPassword");
            return (Criteria) this;
        }

        public Criteria andOrdinaryPasswordNotLike(String value) {
            addCriterion("ordinary_password not like", value, "ordinaryPassword");
            return (Criteria) this;
        }

        public Criteria andOrdinaryPasswordIn(List<String> values) {
            addCriterion("ordinary_password in", values, "ordinaryPassword");
            return (Criteria) this;
        }

        public Criteria andOrdinaryPasswordNotIn(List<String> values) {
            addCriterion("ordinary_password not in", values, "ordinaryPassword");
            return (Criteria) this;
        }

        public Criteria andOrdinaryPasswordBetween(String value1, String value2) {
            addCriterion("ordinary_password between", value1, value2, "ordinaryPassword");
            return (Criteria) this;
        }

        public Criteria andOrdinaryPasswordNotBetween(String value1, String value2) {
            addCriterion("ordinary_password not between", value1, value2, "ordinaryPassword");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNameIsNull() {
            addCriterion("ordinary_name is null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNameIsNotNull() {
            addCriterion("ordinary_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNameEqualTo(String value) {
            addCriterion("ordinary_name =", value, "ordinaryName");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNameNotEqualTo(String value) {
            addCriterion("ordinary_name <>", value, "ordinaryName");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNameGreaterThan(String value) {
            addCriterion("ordinary_name >", value, "ordinaryName");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNameGreaterThanOrEqualTo(String value) {
            addCriterion("ordinary_name >=", value, "ordinaryName");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNameLessThan(String value) {
            addCriterion("ordinary_name <", value, "ordinaryName");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNameLessThanOrEqualTo(String value) {
            addCriterion("ordinary_name <=", value, "ordinaryName");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNameLike(String value) {
            addCriterion("ordinary_name like", value, "ordinaryName");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNameNotLike(String value) {
            addCriterion("ordinary_name not like", value, "ordinaryName");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNameIn(List<String> values) {
            addCriterion("ordinary_name in", values, "ordinaryName");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNameNotIn(List<String> values) {
            addCriterion("ordinary_name not in", values, "ordinaryName");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNameBetween(String value1, String value2) {
            addCriterion("ordinary_name between", value1, value2, "ordinaryName");
            return (Criteria) this;
        }

        public Criteria andOrdinaryNameNotBetween(String value1, String value2) {
            addCriterion("ordinary_name not between", value1, value2, "ordinaryName");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTelephoneIsNull() {
            addCriterion("ordinary_telephone is null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTelephoneIsNotNull() {
            addCriterion("ordinary_telephone is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTelephoneEqualTo(String value) {
            addCriterion("ordinary_telephone =", value, "ordinaryTelephone");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTelephoneNotEqualTo(String value) {
            addCriterion("ordinary_telephone <>", value, "ordinaryTelephone");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTelephoneGreaterThan(String value) {
            addCriterion("ordinary_telephone >", value, "ordinaryTelephone");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("ordinary_telephone >=", value, "ordinaryTelephone");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTelephoneLessThan(String value) {
            addCriterion("ordinary_telephone <", value, "ordinaryTelephone");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTelephoneLessThanOrEqualTo(String value) {
            addCriterion("ordinary_telephone <=", value, "ordinaryTelephone");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTelephoneLike(String value) {
            addCriterion("ordinary_telephone like", value, "ordinaryTelephone");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTelephoneNotLike(String value) {
            addCriterion("ordinary_telephone not like", value, "ordinaryTelephone");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTelephoneIn(List<String> values) {
            addCriterion("ordinary_telephone in", values, "ordinaryTelephone");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTelephoneNotIn(List<String> values) {
            addCriterion("ordinary_telephone not in", values, "ordinaryTelephone");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTelephoneBetween(String value1, String value2) {
            addCriterion("ordinary_telephone between", value1, value2, "ordinaryTelephone");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTelephoneNotBetween(String value1, String value2) {
            addCriterion("ordinary_telephone not between", value1, value2, "ordinaryTelephone");
            return (Criteria) this;
        }

        public Criteria andOrdinaryEmailIsNull() {
            addCriterion("ordinary_email is null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryEmailIsNotNull() {
            addCriterion("ordinary_email is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryEmailEqualTo(String value) {
            addCriterion("ordinary_email =", value, "ordinaryEmail");
            return (Criteria) this;
        }

        public Criteria andOrdinaryEmailNotEqualTo(String value) {
            addCriterion("ordinary_email <>", value, "ordinaryEmail");
            return (Criteria) this;
        }

        public Criteria andOrdinaryEmailGreaterThan(String value) {
            addCriterion("ordinary_email >", value, "ordinaryEmail");
            return (Criteria) this;
        }

        public Criteria andOrdinaryEmailGreaterThanOrEqualTo(String value) {
            addCriterion("ordinary_email >=", value, "ordinaryEmail");
            return (Criteria) this;
        }

        public Criteria andOrdinaryEmailLessThan(String value) {
            addCriterion("ordinary_email <", value, "ordinaryEmail");
            return (Criteria) this;
        }

        public Criteria andOrdinaryEmailLessThanOrEqualTo(String value) {
            addCriterion("ordinary_email <=", value, "ordinaryEmail");
            return (Criteria) this;
        }

        public Criteria andOrdinaryEmailLike(String value) {
            addCriterion("ordinary_email like", value, "ordinaryEmail");
            return (Criteria) this;
        }

        public Criteria andOrdinaryEmailNotLike(String value) {
            addCriterion("ordinary_email not like", value, "ordinaryEmail");
            return (Criteria) this;
        }

        public Criteria andOrdinaryEmailIn(List<String> values) {
            addCriterion("ordinary_email in", values, "ordinaryEmail");
            return (Criteria) this;
        }

        public Criteria andOrdinaryEmailNotIn(List<String> values) {
            addCriterion("ordinary_email not in", values, "ordinaryEmail");
            return (Criteria) this;
        }

        public Criteria andOrdinaryEmailBetween(String value1, String value2) {
            addCriterion("ordinary_email between", value1, value2, "ordinaryEmail");
            return (Criteria) this;
        }

        public Criteria andOrdinaryEmailNotBetween(String value1, String value2) {
            addCriterion("ordinary_email not between", value1, value2, "ordinaryEmail");
            return (Criteria) this;
        }

        public Criteria andOrdinarySchoolIsNull() {
            addCriterion("ordinary_school is null");
            return (Criteria) this;
        }

        public Criteria andOrdinarySchoolIsNotNull() {
            addCriterion("ordinary_school is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinarySchoolEqualTo(String value) {
            addCriterion("ordinary_school =", value, "ordinarySchool");
            return (Criteria) this;
        }

        public Criteria andOrdinarySchoolNotEqualTo(String value) {
            addCriterion("ordinary_school <>", value, "ordinarySchool");
            return (Criteria) this;
        }

        public Criteria andOrdinarySchoolGreaterThan(String value) {
            addCriterion("ordinary_school >", value, "ordinarySchool");
            return (Criteria) this;
        }

        public Criteria andOrdinarySchoolGreaterThanOrEqualTo(String value) {
            addCriterion("ordinary_school >=", value, "ordinarySchool");
            return (Criteria) this;
        }

        public Criteria andOrdinarySchoolLessThan(String value) {
            addCriterion("ordinary_school <", value, "ordinarySchool");
            return (Criteria) this;
        }

        public Criteria andOrdinarySchoolLessThanOrEqualTo(String value) {
            addCriterion("ordinary_school <=", value, "ordinarySchool");
            return (Criteria) this;
        }

        public Criteria andOrdinarySchoolLike(String value) {
            addCriterion("ordinary_school like", value, "ordinarySchool");
            return (Criteria) this;
        }

        public Criteria andOrdinarySchoolNotLike(String value) {
            addCriterion("ordinary_school not like", value, "ordinarySchool");
            return (Criteria) this;
        }

        public Criteria andOrdinarySchoolIn(List<String> values) {
            addCriterion("ordinary_school in", values, "ordinarySchool");
            return (Criteria) this;
        }

        public Criteria andOrdinarySchoolNotIn(List<String> values) {
            addCriterion("ordinary_school not in", values, "ordinarySchool");
            return (Criteria) this;
        }

        public Criteria andOrdinarySchoolBetween(String value1, String value2) {
            addCriterion("ordinary_school between", value1, value2, "ordinarySchool");
            return (Criteria) this;
        }

        public Criteria andOrdinarySchoolNotBetween(String value1, String value2) {
            addCriterion("ordinary_school not between", value1, value2, "ordinarySchool");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDeptIsNull() {
            addCriterion("ordinary_dept is null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDeptIsNotNull() {
            addCriterion("ordinary_dept is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDeptEqualTo(String value) {
            addCriterion("ordinary_dept =", value, "ordinaryDept");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDeptNotEqualTo(String value) {
            addCriterion("ordinary_dept <>", value, "ordinaryDept");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDeptGreaterThan(String value) {
            addCriterion("ordinary_dept >", value, "ordinaryDept");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDeptGreaterThanOrEqualTo(String value) {
            addCriterion("ordinary_dept >=", value, "ordinaryDept");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDeptLessThan(String value) {
            addCriterion("ordinary_dept <", value, "ordinaryDept");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDeptLessThanOrEqualTo(String value) {
            addCriterion("ordinary_dept <=", value, "ordinaryDept");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDeptLike(String value) {
            addCriterion("ordinary_dept like", value, "ordinaryDept");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDeptNotLike(String value) {
            addCriterion("ordinary_dept not like", value, "ordinaryDept");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDeptIn(List<String> values) {
            addCriterion("ordinary_dept in", values, "ordinaryDept");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDeptNotIn(List<String> values) {
            addCriterion("ordinary_dept not in", values, "ordinaryDept");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDeptBetween(String value1, String value2) {
            addCriterion("ordinary_dept between", value1, value2, "ordinaryDept");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDeptNotBetween(String value1, String value2) {
            addCriterion("ordinary_dept not between", value1, value2, "ordinaryDept");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTypeIsNull() {
            addCriterion("ordinary_type is null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTypeIsNotNull() {
            addCriterion("ordinary_type is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTypeEqualTo(String value) {
            addCriterion("ordinary_type =", value, "ordinaryType");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTypeNotEqualTo(String value) {
            addCriterion("ordinary_type <>", value, "ordinaryType");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTypeGreaterThan(String value) {
            addCriterion("ordinary_type >", value, "ordinaryType");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ordinary_type >=", value, "ordinaryType");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTypeLessThan(String value) {
            addCriterion("ordinary_type <", value, "ordinaryType");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTypeLessThanOrEqualTo(String value) {
            addCriterion("ordinary_type <=", value, "ordinaryType");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTypeLike(String value) {
            addCriterion("ordinary_type like", value, "ordinaryType");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTypeNotLike(String value) {
            addCriterion("ordinary_type not like", value, "ordinaryType");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTypeIn(List<String> values) {
            addCriterion("ordinary_type in", values, "ordinaryType");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTypeNotIn(List<String> values) {
            addCriterion("ordinary_type not in", values, "ordinaryType");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTypeBetween(String value1, String value2) {
            addCriterion("ordinary_type between", value1, value2, "ordinaryType");
            return (Criteria) this;
        }

        public Criteria andOrdinaryTypeNotBetween(String value1, String value2) {
            addCriterion("ordinary_type not between", value1, value2, "ordinaryType");
            return (Criteria) this;
        }

        public Criteria andOrdinaryJurisdictionIsNull() {
            addCriterion("ordinary_jurisdiction is null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryJurisdictionIsNotNull() {
            addCriterion("ordinary_jurisdiction is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryJurisdictionEqualTo(String value) {
            addCriterion("ordinary_jurisdiction =", value, "ordinaryJurisdiction");
            return (Criteria) this;
        }

        public Criteria andOrdinaryJurisdictionNotEqualTo(String value) {
            addCriterion("ordinary_jurisdiction <>", value, "ordinaryJurisdiction");
            return (Criteria) this;
        }

        public Criteria andOrdinaryJurisdictionGreaterThan(String value) {
            addCriterion("ordinary_jurisdiction >", value, "ordinaryJurisdiction");
            return (Criteria) this;
        }

        public Criteria andOrdinaryJurisdictionGreaterThanOrEqualTo(String value) {
            addCriterion("ordinary_jurisdiction >=", value, "ordinaryJurisdiction");
            return (Criteria) this;
        }

        public Criteria andOrdinaryJurisdictionLessThan(String value) {
            addCriterion("ordinary_jurisdiction <", value, "ordinaryJurisdiction");
            return (Criteria) this;
        }

        public Criteria andOrdinaryJurisdictionLessThanOrEqualTo(String value) {
            addCriterion("ordinary_jurisdiction <=", value, "ordinaryJurisdiction");
            return (Criteria) this;
        }

        public Criteria andOrdinaryJurisdictionLike(String value) {
            addCriterion("ordinary_jurisdiction like", value, "ordinaryJurisdiction");
            return (Criteria) this;
        }

        public Criteria andOrdinaryJurisdictionNotLike(String value) {
            addCriterion("ordinary_jurisdiction not like", value, "ordinaryJurisdiction");
            return (Criteria) this;
        }

        public Criteria andOrdinaryJurisdictionIn(List<String> values) {
            addCriterion("ordinary_jurisdiction in", values, "ordinaryJurisdiction");
            return (Criteria) this;
        }

        public Criteria andOrdinaryJurisdictionNotIn(List<String> values) {
            addCriterion("ordinary_jurisdiction not in", values, "ordinaryJurisdiction");
            return (Criteria) this;
        }

        public Criteria andOrdinaryJurisdictionBetween(String value1, String value2) {
            addCriterion("ordinary_jurisdiction between", value1, value2, "ordinaryJurisdiction");
            return (Criteria) this;
        }

        public Criteria andOrdinaryJurisdictionNotBetween(String value1, String value2) {
            addCriterion("ordinary_jurisdiction not between", value1, value2, "ordinaryJurisdiction");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDemoIsNull() {
            addCriterion("ordinary_demo is null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDemoIsNotNull() {
            addCriterion("ordinary_demo is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDemoEqualTo(String value) {
            addCriterion("ordinary_demo =", value, "ordinaryDemo");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDemoNotEqualTo(String value) {
            addCriterion("ordinary_demo <>", value, "ordinaryDemo");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDemoGreaterThan(String value) {
            addCriterion("ordinary_demo >", value, "ordinaryDemo");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDemoGreaterThanOrEqualTo(String value) {
            addCriterion("ordinary_demo >=", value, "ordinaryDemo");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDemoLessThan(String value) {
            addCriterion("ordinary_demo <", value, "ordinaryDemo");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDemoLessThanOrEqualTo(String value) {
            addCriterion("ordinary_demo <=", value, "ordinaryDemo");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDemoLike(String value) {
            addCriterion("ordinary_demo like", value, "ordinaryDemo");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDemoNotLike(String value) {
            addCriterion("ordinary_demo not like", value, "ordinaryDemo");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDemoIn(List<String> values) {
            addCriterion("ordinary_demo in", values, "ordinaryDemo");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDemoNotIn(List<String> values) {
            addCriterion("ordinary_demo not in", values, "ordinaryDemo");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDemoBetween(String value1, String value2) {
            addCriterion("ordinary_demo between", value1, value2, "ordinaryDemo");
            return (Criteria) this;
        }

        public Criteria andOrdinaryDemoNotBetween(String value1, String value2) {
            addCriterion("ordinary_demo not between", value1, value2, "ordinaryDemo");
            return (Criteria) this;
        }

        public Criteria andOrdinaryMoneyIsNull() {
            addCriterion("ordinary_money is null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryMoneyIsNotNull() {
            addCriterion("ordinary_money is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinaryMoneyEqualTo(Double value) {
            addCriterion("ordinary_money =", value, "ordinaryMoney");
            return (Criteria) this;
        }

        public Criteria andOrdinaryMoneyNotEqualTo(Double value) {
            addCriterion("ordinary_money <>", value, "ordinaryMoney");
            return (Criteria) this;
        }

        public Criteria andOrdinaryMoneyGreaterThan(Double value) {
            addCriterion("ordinary_money >", value, "ordinaryMoney");
            return (Criteria) this;
        }

        public Criteria andOrdinaryMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("ordinary_money >=", value, "ordinaryMoney");
            return (Criteria) this;
        }

        public Criteria andOrdinaryMoneyLessThan(Double value) {
            addCriterion("ordinary_money <", value, "ordinaryMoney");
            return (Criteria) this;
        }

        public Criteria andOrdinaryMoneyLessThanOrEqualTo(Double value) {
            addCriterion("ordinary_money <=", value, "ordinaryMoney");
            return (Criteria) this;
        }

        public Criteria andOrdinaryMoneyIn(List<Double> values) {
            addCriterion("ordinary_money in", values, "ordinaryMoney");
            return (Criteria) this;
        }

        public Criteria andOrdinaryMoneyNotIn(List<Double> values) {
            addCriterion("ordinary_money not in", values, "ordinaryMoney");
            return (Criteria) this;
        }

        public Criteria andOrdinaryMoneyBetween(Double value1, Double value2) {
            addCriterion("ordinary_money between", value1, value2, "ordinaryMoney");
            return (Criteria) this;
        }

        public Criteria andOrdinaryMoneyNotBetween(Double value1, Double value2) {
            addCriterion("ordinary_money not between", value1, value2, "ordinaryMoney");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_ordinary
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 14 13:07:44 AWST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_ordinary
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}