package com.yh.web.pojo;

public class UserAdminKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_admin.admin_id
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private Integer adminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_admin.admin_id
     *
     * @return the value of t_user_admin.admin_id
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_admin.admin_id
     *
     * @param adminId the value for t_user_admin.admin_id
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
}