package com.yh.web.pojo;

public class UserOrdinary extends UserOrdinaryKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ordinary.ordinary_number
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private String ordinaryNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ordinary.ordinary_username
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private String ordinaryUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ordinary.ordinary_password
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private String ordinaryPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ordinary.ordinary_name
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private String ordinaryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ordinary.ordinary_telephone
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private String ordinaryTelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ordinary.ordinary_email
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private String ordinaryEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ordinary.ordinary_school
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private String ordinarySchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ordinary.ordinary_dept
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private String ordinaryDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ordinary.ordinary_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private String ordinaryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ordinary.ordinary_jurisdiction
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private String ordinaryJurisdiction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ordinary.ordinary_demo
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private String ordinaryDemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ordinary.ordinary_money
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    private Double ordinaryMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ordinary.ordinary_number
     *
     * @return the value of t_user_ordinary.ordinary_number
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getOrdinaryNumber() {
        return ordinaryNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ordinary.ordinary_number
     *
     * @param ordinaryNumber the value for t_user_ordinary.ordinary_number
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrdinaryNumber(String ordinaryNumber) {
        this.ordinaryNumber = ordinaryNumber == null ? null : ordinaryNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ordinary.ordinary_username
     *
     * @return the value of t_user_ordinary.ordinary_username
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getOrdinaryUsername() {
        return ordinaryUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ordinary.ordinary_username
     *
     * @param ordinaryUsername the value for t_user_ordinary.ordinary_username
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrdinaryUsername(String ordinaryUsername) {
        this.ordinaryUsername = ordinaryUsername == null ? null : ordinaryUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ordinary.ordinary_password
     *
     * @return the value of t_user_ordinary.ordinary_password
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getOrdinaryPassword() {
        return ordinaryPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ordinary.ordinary_password
     *
     * @param ordinaryPassword the value for t_user_ordinary.ordinary_password
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrdinaryPassword(String ordinaryPassword) {
        this.ordinaryPassword = ordinaryPassword == null ? null : ordinaryPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ordinary.ordinary_name
     *
     * @return the value of t_user_ordinary.ordinary_name
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getOrdinaryName() {
        return ordinaryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ordinary.ordinary_name
     *
     * @param ordinaryName the value for t_user_ordinary.ordinary_name
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrdinaryName(String ordinaryName) {
        this.ordinaryName = ordinaryName == null ? null : ordinaryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ordinary.ordinary_telephone
     *
     * @return the value of t_user_ordinary.ordinary_telephone
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getOrdinaryTelephone() {
        return ordinaryTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ordinary.ordinary_telephone
     *
     * @param ordinaryTelephone the value for t_user_ordinary.ordinary_telephone
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrdinaryTelephone(String ordinaryTelephone) {
        this.ordinaryTelephone = ordinaryTelephone == null ? null : ordinaryTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ordinary.ordinary_email
     *
     * @return the value of t_user_ordinary.ordinary_email
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getOrdinaryEmail() {
        return ordinaryEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ordinary.ordinary_email
     *
     * @param ordinaryEmail the value for t_user_ordinary.ordinary_email
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrdinaryEmail(String ordinaryEmail) {
        this.ordinaryEmail = ordinaryEmail == null ? null : ordinaryEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ordinary.ordinary_school
     *
     * @return the value of t_user_ordinary.ordinary_school
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getOrdinarySchool() {
        return ordinarySchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ordinary.ordinary_school
     *
     * @param ordinarySchool the value for t_user_ordinary.ordinary_school
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrdinarySchool(String ordinarySchool) {
        this.ordinarySchool = ordinarySchool == null ? null : ordinarySchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ordinary.ordinary_dept
     *
     * @return the value of t_user_ordinary.ordinary_dept
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getOrdinaryDept() {
        return ordinaryDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ordinary.ordinary_dept
     *
     * @param ordinaryDept the value for t_user_ordinary.ordinary_dept
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrdinaryDept(String ordinaryDept) {
        this.ordinaryDept = ordinaryDept == null ? null : ordinaryDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ordinary.ordinary_type
     *
     * @return the value of t_user_ordinary.ordinary_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getOrdinaryType() {
        return ordinaryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ordinary.ordinary_type
     *
     * @param ordinaryType the value for t_user_ordinary.ordinary_type
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrdinaryType(String ordinaryType) {
        this.ordinaryType = ordinaryType == null ? null : ordinaryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ordinary.ordinary_jurisdiction
     *
     * @return the value of t_user_ordinary.ordinary_jurisdiction
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getOrdinaryJurisdiction() {
        return ordinaryJurisdiction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ordinary.ordinary_jurisdiction
     *
     * @param ordinaryJurisdiction the value for t_user_ordinary.ordinary_jurisdiction
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrdinaryJurisdiction(String ordinaryJurisdiction) {
        this.ordinaryJurisdiction = ordinaryJurisdiction == null ? null : ordinaryJurisdiction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ordinary.ordinary_demo
     *
     * @return the value of t_user_ordinary.ordinary_demo
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public String getOrdinaryDemo() {
        return ordinaryDemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ordinary.ordinary_demo
     *
     * @param ordinaryDemo the value for t_user_ordinary.ordinary_demo
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrdinaryDemo(String ordinaryDemo) {
        this.ordinaryDemo = ordinaryDemo == null ? null : ordinaryDemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ordinary.ordinary_money
     *
     * @return the value of t_user_ordinary.ordinary_money
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public Double getOrdinaryMoney() {
        return ordinaryMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ordinary.ordinary_money
     *
     * @param ordinaryMoney the value for t_user_ordinary.ordinary_money
     *
     * @mbg.generated Wed Dec 14 13:07:44 AWST 2022
     */
    public void setOrdinaryMoney(Double ordinaryMoney) {
        this.ordinaryMoney = ordinaryMoney;
    }
}